version = 3.11.5
runner.dialect = scala3

project.git = true
project.excludePaths = [
  "glob:**/sbt-test/**",
  "glob:**/input_sources/**",
  "glob:**/contraband-scala/**",
  "glob:**/zinc/src/test/resources/**",
]

maxColumn = 100
newlines.source = keep

# We use Asterisk style (aka JavaDoc style).
# But we don't want to reformat all the old comments, so:
docstrings.style = keep

# This also seems more idiomatic to include whitespace in import x.{ yyy }
spaces.inImportCurlyBraces = true

# This is more idiomatic Scala.
# http://docs.scala-lang.org/style/indentation.html#methods-with-numerous-arguments
align.openParenCallSite = false
align.openParenDefnSite = false

# For better code clarity
danglingParentheses.callSite = true
danglingParentheses.defnSite = true

# Minimize diffs
rewrite.trailingCommas.style = keep

rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.newSyntax.control = true
rewrite.scala3.optionalBraces.enabled = true
rewrite.scala3.endMarker.insert.breaks.min = 20

fileOverride {
  "glob:**/internal/compiler-bridge/**" {
    rewrite.scala3.convertToNewSyntax = false
    runner.dialect = scala213
  },
  "glob:**/internal/compiler-bridge-test/**" {
    rewrite.scala3.convertToNewSyntax = false
    runner.dialect = scala213
  }
}

fileOverride {
  "glob:**.sbt" {
    runner.dialect = scala3
  }
}
