name: CI
on:
  pull_request:
  push:

jobs:
  test:
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
            distribution: zulu
            jobtype: 1
          - os: ubuntu-latest
            java: 11
            distribution: temurin
            jobtype: 1
          - os: ubuntu-latest
            java: 21
            distribution: zulu
            jobtype: 1
          - os: windows-latest
            java: 8
            distribution: zulu
            jobtype: 2
          - os: ubuntu-latest
            java: 21
            distribution: temurin
            jobtype: 3
          - os: ubuntu-latest
            java: 21
            distribution: temurin
            jobtype: 4
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: sbt
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
    - name: Build and test (1)
      if: ${{ matrix.jobtype == 1 }}
      shell: bash
      run: bin/run-ci.sh
    - name: Build and test (2)
      if: ${{ matrix.jobtype == 2 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF-8 -Dsbt.supershell=never "crossTestBridges" "zincRoot/test" "zincScripted/Test/run"
    - name: Build and test (3)
      if: ${{ matrix.jobtype == 3 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF-8 scalafmtCheckAll scalafmtSbtCheck headerCheck "Test/headerCheck" generateContrabands
        git diff --exit-code
    - name: Benchmark smoke test (4)
      if: ${{ matrix.jobtype == 4 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF-8 "-Dbenchmark.jmhOptions=-f 1 -wi 0 -i 1 -w 1s -r 1s" "runBenchmarks"
