name: CI
on:
  pull_request:
  push:

jobs:
  test:
    name: ${{ matrix.name }}
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Test (Linux, JDK 17)
            os: ubuntu-latest
            java: 17
            jobtype: 1
          - name: Test (Linux, JDK 25)
            os: ubuntu-latest
            java: 25
            jobtype: 1
          - name: Test (Windows, JDK 17)
            os: windows-latest
            java: 17
            jobtype: 2
          - name: Formatting, headers, generated code
            os: ubuntu-latest
            java: 21
            jobtype: 3
          - name: Benchmark smoke test
            os: ubuntu-latest
            java: 21
            jobtype: 4
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Setup JDK
      uses: actions/setup-java@v6
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: sbt
    - name: Setup SBT
      uses: sbt/setup-sbt@6bec67c98f542b9e17369bfca0ec822ac1363194 # v1.1.19
    - name: Build and test (1)
      if: ${{ matrix.jobtype == 1 }}
      shell: bash
      run: bin/run-ci.sh
    - name: Build and test (2)
      if: ${{ matrix.jobtype == 2 }}
      shell: bash
      run: |
        sbt -v --server -Dfile.encoding=UTF-8 -Dsbt.supershell=never "Test/compile" "crossTestBridges" "zincRoot/testFull" "scripted"
    - name: Build and test (3)
      if: ${{ matrix.jobtype == 3 }}
      shell: bash
      run: |
        sbt -v --server -Dfile.encoding=UTF-8 scalafmtCheckRepo headerCheck "Test/headerCheck" generateContrabands
        git diff --exit-code
    - name: Benchmark smoke test (4)
      if: ${{ matrix.jobtype == 4 }}
      shell: bash
      run: |
        sbt -v --server -Dfile.encoding=UTF-8 "-Dbenchmark.jmhOptions=-f 1 -wi 0 -i 1 -w 1s -r 1s" "runBenchmarks"
